// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: pkg/api/services.proto

package api

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{0}
}

type GetMe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMe) Reset() {
	*x = GetMe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMe) ProtoMessage() {}

func (x *GetMe) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMe.ProtoReflect.Descriptor instead.
func (*GetMe) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{1}
}

type UpdateMe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMe) Reset() {
	*x = UpdateMe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMe) ProtoMessage() {}

func (x *UpdateMe) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMe.ProtoReflect.Descriptor instead.
func (*UpdateMe) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{2}
}

type UpdateDeviceToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDeviceToken) Reset() {
	*x = UpdateDeviceToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDeviceToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceToken) ProtoMessage() {}

func (x *UpdateDeviceToken) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceToken.ProtoReflect.Descriptor instead.
func (*UpdateDeviceToken) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{3}
}

type SearchUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SearchUser) Reset() {
	*x = SearchUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUser) ProtoMessage() {}

func (x *SearchUser) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUser.ProtoReflect.Descriptor instead.
func (*SearchUser) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{4}
}

type CreateGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateGame) Reset() {
	*x = CreateGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGame) ProtoMessage() {}

func (x *CreateGame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGame.ProtoReflect.Descriptor instead.
func (*CreateGame) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{5}
}

type GetGames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGames) Reset() {
	*x = GetGames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGames) ProtoMessage() {}

func (x *GetGames) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGames.ProtoReflect.Descriptor instead.
func (*GetGames) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{6}
}

type Login_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Login_Request) Reset() {
	*x = Login_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Request) ProtoMessage() {}

func (x *Login_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Request.ProtoReflect.Descriptor instead.
func (*Login_Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{0, 0}
}

type Login_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *Login_Response) Reset() {
	*x = Login_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Response) ProtoMessage() {}

func (x *Login_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Response.ProtoReflect.Descriptor instead.
func (*Login_Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Login_Response) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetMe_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMe_Request) Reset() {
	*x = GetMe_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMe_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMe_Request) ProtoMessage() {}

func (x *GetMe_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMe_Request.ProtoReflect.Descriptor instead.
func (*GetMe_Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{1, 0}
}

type GetMe_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetMe_Response) Reset() {
	*x = GetMe_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMe_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMe_Response) ProtoMessage() {}

func (x *GetMe_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMe_Response.ProtoReflect.Descriptor instead.
func (*GetMe_Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetMe_Response) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateMe_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string      `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Color    PlayerColor `protobuf:"varint,2,opt,name=color,proto3,enum=api.PlayerColor" json:"color,omitempty"`
}

func (x *UpdateMe_Request) Reset() {
	*x = UpdateMe_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMe_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMe_Request) ProtoMessage() {}

func (x *UpdateMe_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMe_Request.ProtoReflect.Descriptor instead.
func (*UpdateMe_Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UpdateMe_Request) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateMe_Request) GetColor() PlayerColor {
	if x != nil {
		return x.Color
	}
	return PlayerColor_BLUE
}

type UpdateMe_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UpdateMe_Response) Reset() {
	*x = UpdateMe_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMe_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMe_Response) ProtoMessage() {}

func (x *UpdateMe_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMe_Response.ProtoReflect.Descriptor instead.
func (*UpdateMe_Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{2, 1}
}

func (x *UpdateMe_Response) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateDeviceToken_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceToken []byte `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
}

func (x *UpdateDeviceToken_Request) Reset() {
	*x = UpdateDeviceToken_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDeviceToken_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceToken_Request) ProtoMessage() {}

func (x *UpdateDeviceToken_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceToken_Request.ProtoReflect.Descriptor instead.
func (*UpdateDeviceToken_Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UpdateDeviceToken_Request) GetDeviceToken() []byte {
	if x != nil {
		return x.DeviceToken
	}
	return nil
}

type UpdateDeviceToken_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDeviceToken_Response) Reset() {
	*x = UpdateDeviceToken_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDeviceToken_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceToken_Response) ProtoMessage() {}

func (x *UpdateDeviceToken_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceToken_Response.ProtoReflect.Descriptor instead.
func (*UpdateDeviceToken_Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{3, 1}
}

type SearchUser_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *SearchUser_Request) Reset() {
	*x = SearchUser_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUser_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUser_Request) ProtoMessage() {}

func (x *SearchUser_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUser_Request.ProtoReflect.Descriptor instead.
func (*SearchUser_Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SearchUser_Request) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type SearchUser_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *SearchUser_Response) Reset() {
	*x = SearchUser_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUser_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUser_Response) ProtoMessage() {}

func (x *SearchUser_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUser_Response.ProtoReflect.Descriptor instead.
func (*SearchUser_Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{4, 1}
}

func (x *SearchUser_Response) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateGame_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []string `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *CreateGame_Request) Reset() {
	*x = CreateGame_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGame_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGame_Request) ProtoMessage() {}

func (x *CreateGame_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGame_Request.ProtoReflect.Descriptor instead.
func (*CreateGame_Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateGame_Request) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

type CreateGame_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateGame_Response) Reset() {
	*x = CreateGame_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGame_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGame_Response) ProtoMessage() {}

func (x *CreateGame_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGame_Response.ProtoReflect.Descriptor instead.
func (*CreateGame_Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{5, 1}
}

type GetGames_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGames_Request) Reset() {
	*x = GetGames_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGames_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGames_Request) ProtoMessage() {}

func (x *GetGames_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGames_Request.ProtoReflect.Descriptor instead.
func (*GetGames_Request) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{6, 0}
}

type GetGames_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games []*Game `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
}

func (x *GetGames_Response) Reset() {
	*x = GetGames_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_services_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGames_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGames_Response) ProtoMessage() {}

func (x *GetGames_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_services_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGames_Response.ProtoReflect.Descriptor instead.
func (*GetGames_Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_services_proto_rawDescGZIP(), []int{6, 1}
}

func (x *GetGames_Response) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

var File_pkg_api_services_proto protoreflect.FileDescriptor

var file_pkg_api_services_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76,
	0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x6b, 0x67,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3d, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x29, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x3d,
	0x0a, 0x05, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x84, 0x01,
	0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x1a, 0x4d, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x1a, 0x29, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x2c, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x5c, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65,
	0x72, 0x1a, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x1a, 0x2b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x22, 0x3d, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x1a,
	0x23, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x42, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x1a, 0x09, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x32, 0xbf, 0x04, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x63,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x31, 0x92, 0x41, 0x0e, 0x62, 0x0c, 0x0a, 0x0a, 0x0a, 0x06, 0x42, 0x65, 0x61, 0x72, 0x65,
	0x72, 0x12, 0x00, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x3a, 0x01, 0x2a, 0x22, 0x15, 0x2f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x5d, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x12, 0x12, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x92, 0x41, 0x0e, 0x62, 0x0c, 0x0a, 0x0a, 0x0a, 0x06,
	0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x12, 0x00, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12,
	0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x65, 0x12, 0x69, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x12, 0x15,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x92,
	0x41, 0x0e, 0x62, 0x0c, 0x0a, 0x0a, 0x0a, 0x06, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x12, 0x00,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x3a, 0x01, 0x2a, 0x22, 0x12, 0x2f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x12, 0x91, 0x01,
	0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x92, 0x41, 0x0e, 0x62, 0x0c, 0x0a, 0x0a, 0x0a, 0x06, 0x42,
	0x65, 0x61, 0x72, 0x65, 0x72, 0x12, 0x00, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x3a, 0x01, 0x2a,
	0x22, 0x1f, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x65, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x73, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x32, 0x92, 0x41, 0x0e, 0x62, 0x0c, 0x0a, 0x0a, 0x0a, 0x06, 0x42, 0x65, 0x61,
	0x72, 0x65, 0x72, 0x12, 0x00, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a, 0x22, 0x16,
	0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x32, 0xe8, 0x01, 0x0a, 0x05, 0x47, 0x61, 0x6d, 0x65, 0x73,
	0x12, 0x71, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x30, 0x92, 0x41, 0x0e, 0x62, 0x0c, 0x0a, 0x0a, 0x0a, 0x06, 0x42, 0x65, 0x61, 0x72,
	0x65, 0x72, 0x12, 0x00, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x3a, 0x01, 0x2a, 0x22, 0x14, 0x2f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x12, 0x6c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x12,
	0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x31,
	0x92, 0x41, 0x0e, 0x62, 0x0c, 0x0a, 0x0a, 0x0a, 0x06, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x12,
	0x00, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x42, 0xf8, 0x01, 0x92, 0x41, 0xbb, 0x01, 0x52, 0x53, 0x0a, 0x03, 0x34, 0x30, 0x31, 0x12,
	0x4c, 0x0a, 0x4a, 0x59, 0x6f, 0x75, 0x20, 0x68, 0x61, 0x76, 0x65, 0x20, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x64, 0x20, 0x6e, 0x6f, 0x20, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x72, 0x20, 0x74,
	0x68, 0x65, 0x20, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x64, 0x20, 0x69, 0x73, 0x20, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x5a, 0x64, 0x0a,
	0x62, 0x0a, 0x06, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x12, 0x58, 0x08, 0x02, 0x12, 0x43, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x20, 0x74, 0x68, 0x65, 0x20, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x77,
	0x69, 0x74, 0x68, 0x20, 0x74, 0x68, 0x65, 0x20, 0x60, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x3a,
	0x20, 0x60, 0x20, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x2c, 0x20, 0x65, 0x2e, 0x67, 0x2e, 0x20,
	0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x20, 0x61, 0x62, 0x63, 0x64, 0x65, 0x31, 0x32, 0x33, 0x34,
	0x35, 0x2e, 0x1a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x20, 0x02, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x68, 0x65, 0x73, 0x74, 0x6e, 0x75, 0x74, 0x34, 0x32, 0x2f, 0x74, 0x65, 0x72, 0x72, 0x61,
	0x66, 0x6f, 0x72, 0x6d, 0x69, 0x6e, 0x67, 0x2d, 0x6d, 0x61, 0x72, 0x73, 0x2d, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_services_proto_rawDescOnce sync.Once
	file_pkg_api_services_proto_rawDescData = file_pkg_api_services_proto_rawDesc
)

func file_pkg_api_services_proto_rawDescGZIP() []byte {
	file_pkg_api_services_proto_rawDescOnce.Do(func() {
		file_pkg_api_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_services_proto_rawDescData)
	})
	return file_pkg_api_services_proto_rawDescData
}

var file_pkg_api_services_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pkg_api_services_proto_goTypes = []any{
	(*Login)(nil),                      // 0: api.Login
	(*GetMe)(nil),                      // 1: api.GetMe
	(*UpdateMe)(nil),                   // 2: api.UpdateMe
	(*UpdateDeviceToken)(nil),          // 3: api.UpdateDeviceToken
	(*SearchUser)(nil),                 // 4: api.SearchUser
	(*CreateGame)(nil),                 // 5: api.CreateGame
	(*GetGames)(nil),                   // 6: api.GetGames
	(*Login_Request)(nil),              // 7: api.Login.Request
	(*Login_Response)(nil),             // 8: api.Login.Response
	(*GetMe_Request)(nil),              // 9: api.GetMe.Request
	(*GetMe_Response)(nil),             // 10: api.GetMe.Response
	(*UpdateMe_Request)(nil),           // 11: api.UpdateMe.Request
	(*UpdateMe_Response)(nil),          // 12: api.UpdateMe.Response
	(*UpdateDeviceToken_Request)(nil),  // 13: api.UpdateDeviceToken.Request
	(*UpdateDeviceToken_Response)(nil), // 14: api.UpdateDeviceToken.Response
	(*SearchUser_Request)(nil),         // 15: api.SearchUser.Request
	(*SearchUser_Response)(nil),        // 16: api.SearchUser.Response
	(*CreateGame_Request)(nil),         // 17: api.CreateGame.Request
	(*CreateGame_Response)(nil),        // 18: api.CreateGame.Response
	(*GetGames_Request)(nil),           // 19: api.GetGames.Request
	(*GetGames_Response)(nil),          // 20: api.GetGames.Response
	(*User)(nil),                       // 21: api.User
	(PlayerColor)(0),                   // 22: api.PlayerColor
	(*Game)(nil),                       // 23: api.Game
}
var file_pkg_api_services_proto_depIdxs = []int32{
	21, // 0: api.Login.Response.user:type_name -> api.User
	21, // 1: api.GetMe.Response.user:type_name -> api.User
	22, // 2: api.UpdateMe.Request.color:type_name -> api.PlayerColor
	21, // 3: api.UpdateMe.Response.user:type_name -> api.User
	21, // 4: api.SearchUser.Response.users:type_name -> api.User
	23, // 5: api.GetGames.Response.games:type_name -> api.Game
	7,  // 6: api.Users.Login:input_type -> api.Login.Request
	9,  // 7: api.Users.GetMe:input_type -> api.GetMe.Request
	11, // 8: api.Users.UpdateMe:input_type -> api.UpdateMe.Request
	13, // 9: api.Users.UpdateDeviceToken:input_type -> api.UpdateDeviceToken.Request
	15, // 10: api.Users.SearchUser:input_type -> api.SearchUser.Request
	17, // 11: api.Games.CreateGame:input_type -> api.CreateGame.Request
	19, // 12: api.Games.GetGames:input_type -> api.GetGames.Request
	8,  // 13: api.Users.Login:output_type -> api.Login.Response
	10, // 14: api.Users.GetMe:output_type -> api.GetMe.Response
	12, // 15: api.Users.UpdateMe:output_type -> api.UpdateMe.Response
	14, // 16: api.Users.UpdateDeviceToken:output_type -> api.UpdateDeviceToken.Response
	16, // 17: api.Users.SearchUser:output_type -> api.SearchUser.Response
	18, // 18: api.Games.CreateGame:output_type -> api.CreateGame.Response
	20, // 19: api.Games.GetGames:output_type -> api.GetGames.Response
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_api_services_proto_init() }
func file_pkg_api_services_proto_init() {
	if File_pkg_api_services_proto != nil {
		return
	}
	file_pkg_api_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_services_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetMe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDeviceToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SearchUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetGames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Login_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Login_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetMe_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetMe_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMe_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMe_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDeviceToken_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDeviceToken_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*SearchUser_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*SearchUser_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGame_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGame_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*GetGames_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_services_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*GetGames_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_api_services_proto_goTypes,
		DependencyIndexes: file_pkg_api_services_proto_depIdxs,
		MessageInfos:      file_pkg_api_services_proto_msgTypes,
	}.Build()
	File_pkg_api_services_proto = out.File
	file_pkg_api_services_proto_rawDesc = nil
	file_pkg_api_services_proto_goTypes = nil
	file_pkg_api_services_proto_depIdxs = nil
}
